### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by Sm00g15** [clauseHQ/clause-model-library#7]
This is totally unrelated, but clause.io doesn't seem to have an ssl cert...the project sounds awesome and I don't want anybody getting blocked from visiting the site!

![screen shot 2018-09-18 at 2 31 49 pm](https://user-images.githubusercontent.com/14209806/45660992-a3d11800-bb4f-11e8-9c3f-966176e7fe5a.jpg)

**Comment by mttrbrts** [comment]
Eeek! Thanks for the feedback. We'll get on to that right away!

**Comment by Sm00g15** [comment]
Sweeeetttt!!! Are you guys looking for any devs to help with the project at the moment?

**Comment by mttrbrts** [comment]
We're always open to new contributions to the [Accord Project ](https://accordproject.org/). Check out the [docs](https://docs.accordproject.org) and [GitHub](https://github.com/accordproject) page for more details. 

Clause isn't hiring right now, but keep an eye on https://angel.co/clause

**Comment by mttrbrts** [comment]
All done. Thanks @Sm00g15
